### ISSUE TITLE
Support wired networks

### ISSUE THREAD

**Issue by mlevison** [ivpn/desktop-app-ui#1]
# Feature request

## Description

Our house has a wired network (i.e. CAT-5 ethernet cabling) that I use in preference to the WiFi. IVPN doesn't recognize the wired network.

## Describe the solution you'd like

If you have a solution in mind, please describe it.

## Describe alternatives you've considered

I unplug, However our wifi is slower than the wired network,

**Comment by stenya** [comment]
Hi @mlevison,
can you, please, clarify your issue in more detail?

**Comment by mlevison** [comment]
Does this picture help: https://i.imgur.com/79N79kT.png

**Comment by stenya** [comment]
@mlevison 
Ok, thanks. Now I understand what you are speaking about.

The sign "no WiFi connection" is just informing that there is no active WiFi connection :) . And the functionality 'Trusted / Untrusted networks control' is not applicable (if you activated it).

There is no issue here.
You can use IVPN as usual. It doesn't matter which connection you use (wired or not).
